# Change these first
owner: forwardemail # Your GitHub organization or username, where this repository lives
repo: status.forwardemail.net # The name of this repository

sites:
  - name: https://forwardemail.net (curl)
    url: https://forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico

  - name: forwardemail.net:443 (IPv4)
    url: forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 443
    check: "tcp-ping"
  - name: forwardemail.net:443 (IPv6)
    url: forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 443
    check: "tcp-ping"
    ipv6: false

  - name: forwardemail.net:80 (IPv4)
    url: forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 80
    check: "tcp-ping"
  - name: forwardemail.net:80 (IPv6)
    url: forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 80
    check: "tcp-ping"
    ipv6: false

  - name: https://api.forwardemail.net (curl)
    url: https://api.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico

  - name: api.forwardemail.net:443 (IPv4)
    url: api.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 443
    check: "tcp-ping"
  - name: api.forwardemail.net:443 (IPv6)
    url: api.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 443
    check: "tcp-ping"
    ipv6: false

  - name: api.forwardemail.net:80 (IPv4)
    url: api.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 80
    check: "tcp-ping"
  - name: api.forwardemail.net:80 (IPv6)
    url: api.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 80
    check: "tcp-ping"
    ipv6: false

  - name: smtp.forwardemail.net:587 (IPv4)
    url: smtp.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 587
    check: "tcp-ping"
  - name: smtp.forwardemail.net:587 (IPv6)
    url: smtp.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 587
    check: "tcp-ping"
    ipv6: false

  - name: smtp.forwardemail.net:2587 (IPv4)
    url: smtp.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 2587
    check: "tcp-ping"
  - name: smtp.forwardemail.net:2587 (IPv6)
    url: smtp.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 2587
    check: "tcp-ping"
    ipv6: false

  - name: smtp.forwardemail.net:465 (IPv4)
    url: smtp.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 465
    check: "tcp-ping"
  - name: smtp.forwardemail.net:465 (IPv6)
    url: smtp.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 465
    check: "tcp-ping"
    ipv6: false

  - name: smtp.forwardemail.net:2465 (IPv4)
    url: smtp.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 2465
    check: "tcp-ping"
  - name: smtp.forwardemail.net:2465 (IPv6)
    url: smtp.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 2465
    check: "tcp-ping"
    ipv6: false

  - name: smtp.forwardemail.net:25 (IPv4)
    url: smtp.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 25
    check: "tcp-ping"
  - name: smtp.forwardemail.net:25 (IPv6)
    url: smtp.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 25
    check: "tcp-ping"
    ipv6: false

  - name: smtp.forwardemail.net:2525 (IPv4)
    url: smtp.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 2525
    check: "tcp-ping"
  - name: smtp.forwardemail.net:2525 (IPv6)
    url: smtp.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 2525
    check: "tcp-ping"
    ipv6: false

  - name: imap.forwardemail.net:993 (IPv4)
    url: imap.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 993
    check: "tcp-ping"
  - name: imap.forwardemail.net:993 (IPv6)
    url: imap.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 993
    check: "tcp-ping"
    ipv6: false

  - name: imap.forwardemail.net:2993 (IPv4)
    url: imap.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 2993
    check: "tcp-ping"
  - name: imap.forwardemail.net:2993 (IPv6)
    url: imap.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 2993
    check: "tcp-ping"
    ipv6: false

  - name: pop3.forwardemail.net:995 (IPv4)
    url: pop3.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 995
    check: "tcp-ping"
  - name: pop3.forwardemail.net:995 (IPv6)
    url: pop3.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 995
    check: "tcp-ping"
    ipv6: false

  - name: pop3.forwardemail.net:2995 (IPv4)
    url: pop3.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 2995
    check: "tcp-ping"
  - name: pop3.forwardemail.net:2995 (IPv6)
    url: pop3.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 2995
    check: "tcp-ping"
    ipv6: false

  - name: mx1.forwardemail.net:25 (IPv4)
    url: mx1.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 25
    check: "tcp-ping"
  - name: mx1.forwardemail.net:25 (IPv6)
    url: mx1.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 25
    check: "tcp-ping"
    ipv6: false

  - name: mx2.forwardemail.net:25 (IPv4)
    url: mx2.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 25
    check: "tcp-ping"
  - name: mx2.forwardemail.net:25 (IPv6)
    url: mx2.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 25
    check: "tcp-ping"
    ipv6: false

#  - name: https://caldav.forwardemail.net (curl)
#    url: https://caldav.forwardemail.net
#    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico

  - name: caldav.forwardemail.net:443 (IPv4)
    url: caldav.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 443
    check: "tcp-ping"
  - name: caldav.forwardemail.net:443 (IPv6)
    url: caldav.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 443
    check: "tcp-ping"
    ipv6: false

  - name: caldav.forwardemail.net:80 (IPv4)
    url: caldav.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 80
    check: "tcp-ping"
  - name: caldav.forwardemail.net:80 (IPv6)
    url: caldav.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 80
    check: "tcp-ping"
    ipv6: false

  - name: bree.forwardemail.net
    url: bree.forwardemail.net
    icon: https://raw.githubusercontent.com/breejs/bree/master/favicon.ico
    port: 22
    check: "tcp-ping"

  - name: sqlite.forwardemail.net
    url: sqlite.forwardemail.net
    icon: https://sqlite.org/favicon.ico
    port: 22
    check: "tcp-ping"

  - name: forwardemail.net:443 (SSL)
    url: forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 443
    check: "ssl"
  - name: api.forwardemail.net (SSL)
    url: api.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 443
    check: "ssl"
  - name: caldav.forwardemail.net (SSL)
    url: caldav.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 443
    check: "ssl"
  - name: status.forwardemail.net (SSL)
    url: status.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 443
    check: "ssl"
  - name: checkout.forwardemail.net (SSL)
    url: checkout.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 443
    check: "ssl"

  # we cannot test these because they do not allow ping on managed dbs and ip-restricted access list only
  # - name: mongo
  #   url: $MONGO_HOST
  #   icon: https://raw.githubusercontent.com/mongodb/mongo/master/docs/leaf.svg
  #   port: $MONGO_PORT
  #   check: "tcp-ping"
  # - name: logs
  #   url: $LOGS_HOST
  #   icon: https://raw.githubusercontent.com/mongodb/mongo/master/docs/leaf.svg
  #   port: $LOGS_PORT
  #   check: "tcp-ping"
  # - name: redis
  #   url: $REDIS_HOST
  #   icon: https://redis.io/images/favicons/favicon.ico
  #   port: $REDIS_PORT
  #   check: "tcp-ping"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.forwardemail.net
  # baseUrl: /your-repo-name
  logoUrl: https://forwardemail.net/img/logo-square.svg
  favicon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/apple-touch-icon.png
  faviconSvg: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/logo-square.svg
  name: Status Page | Forward Email
  customHeadHtml: "<meta name=\"robots\" content=\"noindex nofollow noarchive noimageindex\">"
  introTitle: "**Forward Email** is the only 100% open-source and privacy-focused email service."
  introMessage: Our status page uses real-time data from our [GitHub repository](https://github.com/forwardemail/status.forwardemail.net).
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://forwardemail.net
    - title: GitHub
      href: https://github.com/forwardemail

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  footer: "**Subscribe to real-time updates:** Visit our [GitHub repository](https://github.com/forwardemail/status.forwardemail.net) and click on the _Notifications_ dropdown and select _All Activity_."
