# Change these first
owner: forwardemail # Your GitHub organization or username, where this repository lives
repo: status.forwardemail.net # The name of this repository

sites:
  - name: forwardemail.net
    url: https://forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
  - name: web-vu-sj-ca (forwardemail.net - Vultr - San Jose, California, USA)
    url: https://45.63.88.165
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    __dangerous__disable_verify_host: true
  - name: web-do-am-nl (forwardemail.net - Digital Ocean - Amsterdam, Netherlands, Europe)
    url: https://159.223.238.2
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    __dangerous__disable_verify_host: true
  - name: api.forwardemail.net
    url: https://api.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
  - name: api-vu-sj-ca (api.forwardemail.net - Vultr - San Jose, California, USA)
    url: https://149.28.198.68
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    __dangerous__disable_verify_host: true
  - name: api-do-am-nl (api.forwardemail.net - Digital Ocean - Amsterdam, Netherlands, Europe)
    url: https://164.92.213.75
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    __dangerous__disable_verify_host: true
  - name: mx1.forwardemail.net
    url: mx1.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 25
    check: "tcp-ping"
  - name: mx2.forwardemail.net
    url: mx2.forwardemail.net
    icon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/favicon.ico
    port: 25
    check: "tcp-ping"
  - name: bree
    url: $IP_ADDRESS_BREE
    icon: https://raw.githubusercontent.com/breejs/bree/master/favicon.ico
    port: 22
    check: "tcp-ping"
  - name: mongo
    url: $IP_ADDRESS_MONGO
    icon: https://raw.githubusercontent.com/mongodb/mongo/master/docs/leaf.svg
    port: 22
    check: "tcp-ping"
  - name: redis
    url: $IP_ADDRESS_REDIS
    icon: https://redis.io/images/favicons/favicon.ico
    port: 22
    check: "tcp-ping"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.forwardemail.net
  # baseUrl: /your-repo-name
  logoUrl: https://forwardemail.net/img/logo-square.svg
  favicon: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/apple-touch-icon.png
  faviconSvg: https://raw.githubusercontent.com/forwardemail/forwardemail.net/master/assets/img/logo-square.svg
  name: Status Page | Forward Email
  customHeadHtml: "<meta name=\"robots\" content=\"noindex nofollow noarchive noimageindex\">"
  introTitle: "**Forward Email** is the only 100% open-source and privacy-focused email service."
  introMessage: Our status page uses real-time data from our [GitHub repository](https://github.com/forwardemail/status.forwardemail.net).
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://forwardemail.net
    - title: GitHub
      href: https://github.com/forwardemail

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  footer: "**Subscribe to real-time updates:** Visit our [GitHub repository](https://github.com/forwardemail/status.forwardemail.net) and click on the _Notifications_ dropdown and select _All Activity_."
