name: "Matrix All Activity Notifications"

on:
  # Issues
  issues:
    types: [opened, closed, reopened]
  # edited, assigned, unassigned, labeled, unlabeled, locked, unlocked, transferred, pinned, unpinned]

  # Issue Comments
  issue_comment:
    types: [created] #, edited, deleted]

  # Pull Requests
  pull_request:
    types: [opened] # , edited, closed]
  # , reopened, assigned, unassigned, review_requested, review_request_removed, labeled, unlabeled, synchronize, converted_to_draft, ready_for_review, locked, unlocked]

  # Pull Request Reviews
  pull_request_review:
    types: [submitted] # , edited, dismissed]

  # Pull Request Review Comments
  pull_request_review_comment:
    types: [created] #, edited, deleted]

  # Pushes to any branch AND tags
  #push:
  #  branches: ['**']
  #  tags: ['**']

  # Releases
  release:
    types: [published] #, unpublished, created, edited, deleted, prereleased, released]

  # Stars
  #watch:
  #  types: [started]

  # Forks
  fork:

  # Discussions
  discussion:
    types: [created, answered] #, edited, deleted, pinned, unpinned, locked, unlocked, transferred, category_changed, answered, unanswered]

  # Discussion Comments
  discussion_comment:
    types: [created] #, edited, deleted]

  # Wiki
  gollum:

  # Milestones
  milestone:
    types: [closed] # [created, closed, opened, edited, deleted]

  # Labels
  #label:
  #  types: [created, edited, deleted]

  # Branch/Tag creation and deletion
  create:
  delete:

  # Deployment
  deployment:
  deployment_status:

  # Pages
  # page_build:

  # Repository dispatch
  # repository_dispatch:

  # Public (when repo goes public)
  public:

  # Check runs
  #check_run:
  #  types: [created, completed, rerequested, requested_action]

  # Check suites
  #check_suite:
  #  types: [completed, requested, rerequested]

  # Branch protection rules
  #branch_protection_rule:
  #  types: [created, edited, deleted]

  # Registry packages
  registry_package:
    types: [published, updated]

  # Status (commit status)
  status:

jobs:
  notify-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Determine activity type and format message
        id: format
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"

          # Set default values
          ICON="📝"
          TITLE="GitHub Activity"
          DESCRIPTION=""
          URL="${{ github.event.repository.html_url }}"
          ACTOR="${{ github.actor }}"

          case "${{ github.event_name }}" in
            "issues")
              ICON="🐛"
              case "${{ github.event.action }}" in
                "opened") TITLE="New Issue Opened" ;;
                "closed") TITLE="Issue Closed" ;;
                "reopened") TITLE="Issue Reopened" ;;
                "edited") TITLE="Issue Edited" ;;
                "assigned") TITLE="Issue Assigned" ;;
                "labeled") TITLE="Issue Labeled" ;;
                *) TITLE="Issue ${{ github.event.action }}" ;;
              esac
              DESCRIPTION="${{ github.event.issue.title }}"
              URL="${{ github.event.issue.html_url }}"
              ;;
            "issue_comment")
              ICON="💬"
              TITLE="Issue Comment ${{ github.event.action }}"
              DESCRIPTION="On: ${{ github.event.issue.title }}"
              URL="${{ github.event.comment.html_url }}"
              ;;
            "pull_request")
              ICON="🔀"
              case "${{ github.event.action }}" in
                "opened") TITLE="New Pull Request" ;;
                "closed")
                  if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
                    TITLE="Pull Request Merged"
                    ICON="✅"
                  else
                    TITLE="Pull Request Closed"
                  fi
                  ;;
                "reopened") TITLE="Pull Request Reopened" ;;
                "ready_for_review") TITLE="Pull Request Ready for Review" ;;
                *) TITLE="Pull Request ${{ github.event.action }}" ;;
              esac
              DESCRIPTION="${{ github.event.pull_request.title }}"
              URL="${{ github.event.pull_request.html_url }}"
              ;;
            "pull_request_review")
              ICON="👀"
              TITLE="Pull Request Review ${{ github.event.action }}"
              DESCRIPTION="On: ${{ github.event.pull_request.title }}"
              URL="${{ github.event.review.html_url }}"
              ;;
            "pull_request_review_comment")
              ICON="💭"
              TITLE="PR Review Comment ${{ github.event.action }}"
              DESCRIPTION="On: ${{ github.event.pull_request.title }}"
              URL="${{ github.event.comment.html_url }}"
              ;;
            "push")
              ICON="📤"
              if [[ "${{ github.ref }}" == refs/tags/* ]]; then
                ICON="🏷️"
                TITLE="Tag Pushed"
                DESCRIPTION="Tag: ${{ github.ref_name }}"
              else
                TITLE="Push to ${{ github.ref_name }}"
                DESCRIPTION="${{ github.event.head_commit.message }}"
              fi
              URL="${{ github.event.compare }}"
              ;;
            "release")
              ICON="🚀"
              TITLE="Release ${{ github.event.action }}"
              DESCRIPTION="${{ github.event.release.name || github.event.release.tag_name }}"
              URL="${{ github.event.release.html_url }}"
              ;;
            "watch")
              ICON="⭐"
              TITLE="Repository Starred"
              DESCRIPTION="New watcher: ${{ github.actor }}"
              ;;
            "fork")
              ICON="🍴"
              TITLE="Repository Forked"
              DESCRIPTION="By ${{ github.event.forkee.owner.login }}"
              URL="${{ github.event.forkee.html_url }}"
              ;;
            "discussion")
              ICON="💬"
              TITLE="Discussion ${{ github.event.action }}"
              DESCRIPTION="${{ github.event.discussion.title }}"
              URL="${{ github.event.discussion.html_url }}"
              ;;
            "discussion_comment")
              ICON="💬"
              TITLE="Discussion Comment ${{ github.event.action }}"
              DESCRIPTION="On: ${{ github.event.discussion.title }}"
              URL="${{ github.event.comment.html_url }}"
              ;;
            "gollum")
              ICON="📖"
              TITLE="Wiki Updated"
              DESCRIPTION="Pages modified: ${{ join(github.event.pages.*.page_name, ', ') }}"
              ;;
            "milestone")
              ICON="🎯"
              TITLE="Milestone ${{ github.event.action }}"
              DESCRIPTION="${{ github.event.milestone.title }}"
              URL="${{ github.event.milestone.html_url }}"
              ;;
            "label")
              ICON="🏷️"
              TITLE="Label ${{ github.event.action }}"
              DESCRIPTION="${{ github.event.label.name }}"
              ;;
            "create")
              ICON="🌱"
              TITLE="${{ github.event.ref_type }} Created"
              DESCRIPTION="${{ github.event.ref }}"
              ;;
            "delete")
              ICON="🗑️"
              TITLE="${{ github.event.ref_type }} Deleted"
              DESCRIPTION="${{ github.event.ref }}"
              ;;
            "deployment")
              ICON="🚀"
              TITLE="Deployment"
              DESCRIPTION="Environment: ${{ github.event.deployment.environment }}"
              ;;
            "deployment_status")
              ICON="🚀"
              TITLE="Deployment Status"
              DESCRIPTION="State: ${{ github.event.deployment_status.state }}"
              URL="${{ github.event.deployment_status.target_url }}"
              ;;
            "page_build")
              ICON="📄"
              TITLE="Page Build"
              DESCRIPTION="GitHub Pages build"
              ;;
            "repository_dispatch")
              ICON="📡"
              TITLE="Repository Dispatch"
              DESCRIPTION="Event type: ${{ github.event.action }}"
              ;;
            "public")
              ICON="🌍"
              TITLE="Repository Made Public"
              DESCRIPTION="Repository is now public"
              ;;
            "check_run")
              ICON="✅"
              TITLE="Check Run ${{ github.event.action }}"
              DESCRIPTION="${{ github.event.check_run.name }}"
              URL="${{ github.event.check_run.html_url }}"
              ;;
            "check_suite")
              ICON="✅"
              TITLE="Check Suite ${{ github.event.action }}"
              DESCRIPTION="Conclusion: ${{ github.event.check_suite.conclusion }}"
              URL="${{ github.event.check_suite.html_url }}"
              ;;
            "branch_protection_rule")
              ICON="🛡️"
              TITLE="Branch Protection Rule ${{ github.event.action }}"
              DESCRIPTION="Rule updated"
              ;;
            "registry_package")
              ICON="📦"
              TITLE="Package ${{ github.event.action }}"
              DESCRIPTION="${{ github.event.package.name }}"
              URL="${{ github.event.package.html_url }}"
              ;;
            "status")
              ICON="🔍"
              TITLE="Status Update"
              DESCRIPTION="State: ${{ github.event.state }}"
              URL="${{ github.event.target_url }}"
              ;;
            *)
              TITLE="${{ github.event_name }} ${{ github.event.action }}"
              ;;
          esac

          # Output variables
          echo "icon=$ICON" >> $GITHUB_OUTPUT
          echo "title=$TITLE" >> $GITHUB_OUTPUT
          echo "description=$DESCRIPTION" >> $GITHUB_OUTPUT
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "actor=$ACTOR" >> $GITHUB_OUTPUT

      - name: Send Matrix notification
        uses: lkiesow/matrix-notification@v1
        with:
          server: matrix.org
          token: ${{ secrets.MATRIX_TOKEN }}
          room: '!azsMvrsrqEENIcSLOe:matrix.org'
          message: |
            ${{ steps.format.outputs.icon }} ${{ steps.format.outputs.title }}

            Actor: ${{ steps.format.outputs.actor }}
            Repository: ${{ github.repository }}
            ${{ steps.format.outputs.description && format('Details: {0}', steps.format.outputs.description) || '' }}

            Link: ${{ steps.format.outputs.url }}
          formatted_message: |
            ${{ steps.format.outputs.icon }} <b>${{ steps.format.outputs.title }}</b><br><br>
            <b>Actor:</b> ${{ steps.format.outputs.actor }}<br>
            <b>Repository:</b> ${{ github.repository }}<br>
            ${{ steps.format.outputs.description && format('<b>Details:</b> {0}<br>', steps.format.outputs.description) || '' }}
            <br><b>Link:</b> <a href="${{ steps.format.outputs.url }}">${{ steps.format.outputs.url }}</a>
